# Generated by Django 4.2.6 on 2023-11-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0481_alter_realm_uuid_alter_realm_uuid_owner_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realm",
            name="plan_type",
            field=models.PositiveSmallIntegerField(default=11),
        ),
    ]
